
services:
  app:
    image: memenote-app:latest  # 指定镜像名称
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2  # 生产模式
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # 开发模式    
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    # volumes:
      # - ./app:/app/app  # 开发时热重载
    environment:
      - BROKER_HOST=rabbitmq:5672      
      - REDIS_HOST=redis:6379
      - SQLITE_DB_PATH=/app/data/memenote.sqlite3
    

  celery:
    image: memenote-app:latest    
    command: celery -A app.core.celery_app worker --loglevel=info -Q celery,reminder_queue --autoscale=4,2    
    depends_on:
      - redis
      - rabbitmq
    # volumes:
      # - ./app:/app/app  # 开发时热重载
    environment:
      - BROKER_HOST=rabbitmq:5672      
      - REDIS_HOST=redis:6379
    

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true      
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq/mnesia
   

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=yes
    volumes:
      - redis_data:/bitnami/redis/data
   


volumes:
  rabbitmq_data:
  redis_data: