"""Add Note content unique constraint

Revision ID: f538ccda0a95
Revises: 162bed11eac8
Create Date: 2025-03-26 09:48:15.604846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f538ccda0a95'
down_revision: Union[str, None] = '162bed11eac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes') as batch_op:
        batch_op.create_unique_constraint('_user_content_uc', ['user_id', 'content'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('notes') as batch_op:
        batch_op.drop_constraint('_user_content_uc', type_='unique')
    # ### end Alembic commands ###
